name: Itch.io Production Deployment
env:
  itch_project: arthursegato/lofiblockrunner
on:
  push:
jobs:
  Setup-Godot:
    runs-on: ubuntu-latest
    steps:
      - name: Download Godot
        run: wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_mono_linux_x86_64.zip

      - name: Unpack Godot
        run: unzip ./Godot_v4.3-stable_mono_linux_x86_64.zip

      - name: Prepare Godot artifact
        run: |
          mkdir -p ./godot
          mv ./Godot_v4.3-stable_mono_linux_x86_64/Godot_v4.3-stable_mono_linux.x86_64 ./godot/godot
          mv ./Godot_v4.3-stable_mono_linux_x86_64/GodotSharp ./godot/GodotSharp

      - name: Upload Godot artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot
          path: ./godot/

  Build-Linux:
    needs: Setup-Godot
    runs-on: ubuntu-latest
    steps:
      - name: Download Godot artifact
        uses: actions/download-artifact@v4
        with:
          name: godot
          path: ./godot/

      - name: Install Godot PATH
        run: echo "$HOME/godot/*" >> $GITHUB_PATH

      - name: Verify PATH
        run: echo $GITHUB

      - name: Export Game
        run: sudo godot --headless
