name: Itch.io Production Deployment

env:
  itch_project: arthursegato/lofiblockrunner

on:
  push:

jobs:
  Setup-Godot:
    runs-on: ubuntu-latest
    steps:
      - name: Download Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_mono_linux_x86_64.zip
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_mono_export_templates.tpz

      - name: Unpack Godot
        run: |
          unzip Godot_v4.3-stable_mono_linux_x86_64.zip
          unzip Godot_v4.3-stable_mono_export_templates.tpz

      - name: Prepare Godot
        run: |
          mv ./Godot_v4.3-stable_mono_linux_x86_64/Godot_v4.3-stable_mono_linux.x86_64 ./godot-engine/godot
          mv ./Godot_v4.3-stable_mono_linux_x86_64/GodotSharp ./godot-engine/GodotSharp
          mv ./Godot_v4.3-stable_mono_export_templates/templates/* ./godot-engine/

      - name: Upload Godot artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot
          path: ./godot-engine/

  Build-Linux:
    needs: Setup-Godot
    runs-on: ubuntu-latest
    steps:
      - name: Download Godot
        uses: actions/download-artifact@v4
        with:
          name: godot
          path: ./godot-engine/

      - name: Make Godot executable
        run: chmod +x ./godot-engine/godot

      - name: Install Godot and Export Templates
        run: |
          sudo mv ./godot-engine/godot /usr/local/bin/godot
          sudo mv ./godot-engine/GodotSharp /usr/local/bin/GodotSharp
          sudo mv ./godot-engine/* /home/runner/.local/share/godot/export_templates/4.3.stable.mono/

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export Game
        run: godot --headless --path . --export-release "Linux" ./builds/linux/lofiblockrunner.deb
